-- Difesa aggiuntiva per organizzazione; NON sostituisce autorizzazioni per ruolo/progetto.
-- Eseguire come migration owner; utente runtime diverso, NOSUPERUSER NOBYPASSRLS.
-- Ruolo runtime e GRANT vengono configurati nel deployment, non creati con password qui.
BEGIN;
SET LOCAL search_path=dialoga,public;
CREATE FUNCTION current_organization_id() RETURNS uuid LANGUAGE sql STABLE AS $$
 SELECT NULLIF(current_setting('app.organization_id',true),'')::uuid
$$;

ALTER TABLE organization ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_tenant_policy ON organization USING (id=dialoga.current_organization_id()) WITH CHECK (id=dialoga.current_organization_id());
ALTER TABLE organization_membership ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_membership FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_membership_tenant_policy ON organization_membership USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE project ENABLE ROW LEVEL SECURITY;
ALTER TABLE project FORCE ROW LEVEL SECURITY;
CREATE POLICY project_tenant_policy ON project USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE project_membership ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_membership FORCE ROW LEVEL SECURITY;
CREATE POLICY project_membership_tenant_policy ON project_membership USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE organization_permission ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_permission FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_permission_tenant_policy ON organization_permission USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE project_permission ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_permission FORCE ROW LEVEL SECURITY;
CREATE POLICY project_permission_tenant_policy ON project_permission USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE organization_invite ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_invite FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_invite_tenant_policy ON organization_invite USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE invite_project ENABLE ROW LEVEL SECURITY;
ALTER TABLE invite_project FORCE ROW LEVEL SECURITY;
CREATE POLICY invite_project_tenant_policy ON invite_project USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE assistant ENABLE ROW LEVEL SECURITY;
ALTER TABLE assistant FORCE ROW LEVEL SECURITY;
CREATE POLICY assistant_tenant_policy ON assistant USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE assistant_domain ENABLE ROW LEVEL SECURITY;
ALTER TABLE assistant_domain FORCE ROW LEVEL SECURITY;
CREATE POLICY assistant_domain_tenant_policy ON assistant_domain USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE knowledge_source ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_source FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_source_tenant_policy ON knowledge_source USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE source_revision ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_revision FORCE ROW LEVEL SECURITY;
CREATE POLICY source_revision_tenant_policy ON source_revision USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE source_document ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_document FORCE ROW LEVEL SECURITY;
CREATE POLICY source_document_tenant_policy ON source_document USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE knowledge_chunk ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_chunk FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_chunk_tenant_policy ON knowledge_chunk USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE assistant_version ENABLE ROW LEVEL SECURITY;
ALTER TABLE assistant_version FORCE ROW LEVEL SECURITY;
CREATE POLICY assistant_version_tenant_policy ON assistant_version USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE assistant_version_source ENABLE ROW LEVEL SECURITY;
ALTER TABLE assistant_version_source FORCE ROW LEVEL SECURITY;
CREATE POLICY assistant_version_source_tenant_policy ON assistant_version_source USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE conversation ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation FORCE ROW LEVEL SECURITY;
CREATE POLICY conversation_tenant_policy ON conversation USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE message ENABLE ROW LEVEL SECURITY;
ALTER TABLE message FORCE ROW LEVEL SECURITY;
CREATE POLICY message_tenant_policy ON message USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE message_source ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_source FORCE ROW LEVEL SECURITY;
CREATE POLICY message_source_tenant_policy ON message_source USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE message_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_feedback FORCE ROW LEVEL SECURITY;
CREATE POLICY message_feedback_tenant_policy ON message_feedback USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE lead ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead FORCE ROW LEVEL SECURITY;
CREATE POLICY lead_tenant_policy ON lead USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE subscription ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription FORCE ROW LEVEL SECURITY;
CREATE POLICY subscription_tenant_policy ON subscription USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE subscription_addon ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_addon FORCE ROW LEVEL SECURITY;
CREATE POLICY subscription_addon_tenant_policy ON subscription_addon USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE usage_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_event FORCE ROW LEVEL SECURITY;
CREATE POLICY usage_event_tenant_policy ON usage_event USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE api_credential ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_credential FORCE ROW LEVEL SECURITY;
CREATE POLICY api_credential_tenant_policy ON api_credential USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE webhook_endpoint ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_endpoint FORCE ROW LEVEL SECURITY;
CREATE POLICY webhook_endpoint_tenant_policy ON webhook_endpoint USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE webhook_delivery ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_delivery FORCE ROW LEVEL SECURITY;
CREATE POLICY webhook_delivery_tenant_policy ON webhook_delivery USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE job ENABLE ROW LEVEL SECURITY;
ALTER TABLE job FORCE ROW LEVEL SECURITY;
CREATE POLICY job_tenant_policy ON job USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_log_tenant_policy ON audit_log USING (organization_id=dialoga.current_organization_id()) WITH CHECK (organization_id=dialoga.current_organization_id());
COMMIT;
